-- APPLIED — run successfully via the Supabase SQL Editor and verified
-- end-to-end via the anon client: create_show (id/game_code/host_secret,
-- game-code format, N pre-created unclaimed team slots), host_secret
-- resume (correct and incorrect), resolve_game_code, list_open_tables,
-- draft-blocks-claim, claim_table (name trimming, NULL/blank/>20-char
-- rejection, valid controller_token, second-claim rejection), a genuine
-- concurrent-claim race resolving to exactly one winner, get_team_by_token
-- (correct and wrong token), and confirmation that direct anon
-- SELECT/INSERT/UPDATE/DELETE on shows/teams and direct anon
-- INSERT/UPDATE/DELETE on live_show_state all remain blocked while the
-- existing anon SELECT on live_show_state still works.
--
-- Team-joining architecture: host_secret identity, pre-created team slots,
-- and the player/host RPCs needed to join and resume sessions without any
-- real authentication.
--
-- Identity model:
--   game_code       identifies the show for players joining
--   controller_token identifies and authorises one team's phone
--   host_secret      identifies and authorises the host/controller
--
-- shows and teams remain fully locked (RLS enabled, zero grants/policies).
-- Every operation below goes through a narrow SECURITY DEFINER RPC, exactly
-- matching the pattern already established by create_show and
-- poc_set_live_state_test_message. No RLS or grant changes are made to
-- shows, teams, or live_show_state by this migration.

-- ---------------------------------------------------------------------------
-- 1. Schema changes
-- ---------------------------------------------------------------------------

-- shows.host_secret: generated server-side only, once, at show creation.
-- Never exposed via anonymous SELECT (shows keeps zero anon grants). The
-- only way to see it is the one-time create_show response, or by already
-- possessing it and presenting it to get_show_by_host_secret.
alter table public.shows
  add column host_secret uuid not null default gen_random_uuid();

alter table public.shows
  add constraint shows_host_secret_unique unique (host_secret);

comment on column public.shows.host_secret is 'Server-generated credential identifying the host/controller for this show. Returned once by create_show. Never readable via anon SELECT.';

-- teams: allow the pre-created, unclaimed slot state (table_number exists,
-- nobody has joined yet). Existing CHECK/UNIQUE constraints already behave
-- correctly with NULLs (a NULL operand satisfies CHECK; UNIQUE allows
-- multiple NULLs), so neither needs to change.
alter table public.teams
  alter column team_name drop not null;

alter table public.teams
  alter column controller_token drop not null;

alter table public.teams
  alter column controller_token drop default;

comment on column public.teams.team_name is 'NULL until the table is claimed. Set atomically by claim_table, together with controller_token and joined_at.';
comment on column public.teams.controller_token is 'NULL until the table is claimed. Server-generated by claim_table at claim time — never client-supplied, never re-exposed via anon SELECT. Opaque secret used to securely associate a team''s phone session (/play) with this team, without a full auth system. Must be treated as a credential once issued.';

-- ---------------------------------------------------------------------------
-- 2. create_show — replaced (return type is changing, so it must be
--    dropped first; CREATE OR REPLACE cannot change a function's output
--    columns).
--
-- Now also generates host_secret and pre-creates table_count team rows
-- (table_number 1..N, unclaimed) in the same transaction as the show.
-- ---------------------------------------------------------------------------
drop function if exists public.create_show(text, integer);

create function public.create_show(
  p_name text,
  p_table_count integer
)
returns table (id uuid, game_code varchar(12), host_secret uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  -- Uppercase letters and digits, with visually ambiguous characters
  -- removed: no I, O, 0, or 1.
  v_chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  v_code_length int := 6;
  v_candidate_code text;
  v_new_id uuid;
  v_host_secret uuid;
  v_attempt int := 0;
  v_max_attempts int := 10;
begin
  v_host_secret := gen_random_uuid();

  loop
    v_attempt := v_attempt + 1;
    if v_attempt > v_max_attempts then
      raise exception 'Could not generate a unique game code after % attempts', v_max_attempts;
    end if;

    v_candidate_code := '';
    for i in 1..v_code_length loop
      v_candidate_code := v_candidate_code || substr(v_chars, 1 + floor(random() * length(v_chars))::int, 1);
    end loop;

    begin
      insert into public.shows (name, game_code, table_count, host_secret)
      values (p_name, v_candidate_code, p_table_count, v_host_secret)
      returning public.shows.id into v_new_id;

      exit;
    exception
      when unique_violation then
        continue;
    end;
  end loop;

  insert into public.live_show_state (show_id)
  values (v_new_id);

  insert into public.teams (show_id, table_number)
  select v_new_id, generate_series(1, p_table_count);

  return query
    select v_new_id, v_candidate_code::varchar(12), v_host_secret;
end;
$$;

revoke execute on function public.create_show(text, integer) from public;
grant execute on function public.create_show(text, integer) to anon;

-- ---------------------------------------------------------------------------
-- 3. resolve_game_code — public, no auth. Minimal: just enough for /play to
--    find the show and decide whether it's currently joinable.
-- ---------------------------------------------------------------------------
create function public.resolve_game_code(p_game_code text)
returns table (show_id uuid, status text)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
    select public.shows.id, public.shows.status
    from public.shows
    where public.shows.game_code = upper(p_game_code);
end;
$$;

revoke execute on function public.resolve_game_code(text) from public;
grant execute on function public.resolve_game_code(text) to anon;

-- ---------------------------------------------------------------------------
-- 4. list_open_tables — public, no auth. Table numbers and availability
--    only; never team names, tokens, or other team data.
-- ---------------------------------------------------------------------------
create function public.list_open_tables(p_show_id uuid)
returns table (table_number integer, is_available boolean)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
    select public.teams.table_number, (public.teams.joined_at is null) as is_available
    from public.teams
    where public.teams.show_id = p_show_id
    order by public.teams.table_number;
end;
$$;

revoke execute on function public.list_open_tables(uuid) from public;
grant execute on function public.list_open_tables(uuid) to anon;

-- ---------------------------------------------------------------------------
-- 5. claim_table — the one write path for joining. Validates p_team_name
--    itself before touching any row (NULL / empty-after-trim / over 20
--    chars are all rejected here, independent of the teams table CHECK
--    constraint, since that constraint now permits NULL for unclaimed
--    slots and can no longer be relied on alone to guarantee a claimed
--    table has a valid name). Then checks the show exists and is in a
--    joinable state (ready or live) before attempting the claim. The
--    actual claim is a single guarded UPDATE (WHERE joined_at IS NULL),
--    which Postgres's row-level locking makes atomic: if two requests race
--    for the same table, exactly one UPDATE matches a row and succeeds;
--    the other matches zero rows.
-- ---------------------------------------------------------------------------
create function public.claim_table(
  p_show_id uuid,
  p_table_number integer,
  p_team_name text
)
returns table (team_id uuid, controller_token uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_status text;
  v_team_id uuid;
  v_controller_token uuid;
  v_team_name text;
begin
  if p_team_name is null then
    raise exception 'Team name is required';
  end if;

  v_team_name := trim(p_team_name);

  if char_length(v_team_name) = 0 then
    raise exception 'Team name is required';
  end if;

  if char_length(v_team_name) > 20 then
    raise exception 'Team name must be 20 characters or fewer';
  end if;

  select public.shows.status into v_status
  from public.shows
  where public.shows.id = p_show_id;

  if v_status is null then
    raise exception 'Show not found';
  end if;

  if v_status not in ('ready', 'live') then
    raise exception 'Show is not open for joining';
  end if;

  v_controller_token := gen_random_uuid();

  update public.teams
  set team_name = v_team_name,
      controller_token = v_controller_token,
      joined_at = now()
  where public.teams.show_id = p_show_id
    and public.teams.table_number = p_table_number
    and public.teams.joined_at is null
  returning public.teams.id into v_team_id;

  if v_team_id is null then
    raise exception 'Table % is not available', p_table_number;
  end if;

  return query select v_team_id, v_controller_token;
end;
$$;

revoke execute on function public.claim_table(uuid, integer, text) from public;
grant execute on function public.claim_table(uuid, integer, text) to anon;

-- ---------------------------------------------------------------------------
-- 6. get_team_by_token — resume flow for /play. Looked up purely by token;
--    possession of the token is itself the proof of identity. Read-only, so
--    no show-status gate (harmless to let a team see their own state even
--    after a show ends). Future team-mutating RPCs must additionally check
--    shows.status is in an appropriate active state before writing —
--    a controller_token proves identity, not unlimited write authority.
-- ---------------------------------------------------------------------------
create function public.get_team_by_token(p_controller_token uuid)
returns table (
  team_id uuid,
  show_id uuid,
  table_number integer,
  team_name text,
  total_score integer
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
    select public.teams.id, public.teams.show_id, public.teams.table_number,
           public.teams.team_name, public.teams.total_score
    from public.teams
    where public.teams.controller_token = p_controller_token;
end;
$$;

revoke execute on function public.get_team_by_token(uuid) from public;
grant execute on function public.get_team_by_token(uuid) to anon;

-- ---------------------------------------------------------------------------
-- 7. get_show_by_host_secret — resume flow for /control/[showId]. Requires
--    both show_id and host_secret to match together; returns zero rows on
--    any mismatch without distinguishing "wrong secret" from "no such show",
--    to avoid enumeration. This is the first host-only RPC; future
--    host-only actions (e.g. releasing a table) should require host_secret
--    the same way.
-- ---------------------------------------------------------------------------
create function public.get_show_by_host_secret(
  p_show_id uuid,
  p_host_secret uuid
)
returns table (
  id uuid,
  name text,
  game_code varchar(12),
  status text,
  table_count integer
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
    select public.shows.id, public.shows.name, public.shows.game_code,
           public.shows.status, public.shows.table_count
    from public.shows
    where public.shows.id = p_show_id
      and public.shows.host_secret = p_host_secret;
end;
$$;

revoke execute on function public.get_show_by_host_secret(uuid, uuid) from public;
grant execute on function public.get_show_by_host_secret(uuid, uuid) to anon;
